server:
    port: 8181
spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=chat
        username: postgres
        password: saad2000
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                # format_sql: false
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    profiles:
        active: dev
    mail:
        username: saadghajdaoui1@gmail.com
        password: rmogbnfkbbxehjoj
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        required: true
                        enable: true
                    ssl:
                        trust: smtp.gmail.com
                transport:
                    protocol: smtp
